dist: trusty
language: clojure
node_js:
  - "11"
script: lein doo karma-slimer "tests" once
addons:
  chrome: stable
notifications:
  slack:
    on_success: always
    on_failure: always
    rooms:
    - district0x:53vhalUfg0MitsQwzjP5PWdd#travis-ci
  email: false
before_install:
  - nvm install 11.0.0
before_script:
- wget https://dist.ipfs.io/ipfs-update/v1.5.2/ipfs-update_v1.5.2_linux-amd64.tar.gz -O ipfs-update.tar.gz
- tar -xzf ipfs-update.tar.gz
- ipfs-update/ipfs-update install latest
- ipfs init
- ipfs daemon & #> /dev/null &
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
env:
  global:
  - secure: SmHkohgSEyLICpgBs4H9PrHwf5idWAvbEbQ7hRfdImgPRnCf2NroKIAX2saXHHW7Ncw0K3pix+U0x/Ljis0YDaGLlY+NlfXZ6/gEv0ENseJfc6QkDU2Opi4ecG19O8pB7jglUKUHUbDxJy8udProOVmbFf14uOZ/RJ6bjKiqAP806givBJiHyST16SEzpHRIuGd7WRfMC9YejSVc+Lu+BXfVIOsvBELgV6ug5CL/aClkZHNpJgXVuB4a5/whJducF1hHOZhDcC/aXfNq9LnF+5ACr9enk72Y4h6DHI8Ddi6OZSIIe8rK6ZNXAxleth9mpGHUuGsnJfaHfaQlnOJoqYjsU5bE4Y6BbRUBSA9Dk4xhJ/sXsNKGuU3XY7yaBgjaLZJMgQEVofwGByKtVYPXSPa5Zall/qFafxG7pAmfuXikBy3qz78JoltjyAc9ZwzPiH3mKyDni+95LggX0H7Y/h6iWfw4Gs2J6uT0vC+Xzg3d1lRdxXYynQlGW3+VPOTCnHHdmtzTPpSmRHAUFSu5OddT3lCgjgmOQQpubhhxu9L+BqrLYzRMhcwv+aE/NUN3JM4Pgm3OROup1J7ccDo703+bi4QiXtENutcGHv7MfvxjyAUdlsO9fE98GaLICFgf1AGPYns4ArRbDJRotpK04Z69wSXekzZPK6YigfWagOg=
  - secure: oI03f++DStqFlClybmanVKYFXn0wBIizdyDxMul+zYoebTaziJUwMLkGx/Ou8XhU9Awn9DnaAMAiiQ7aOQYlKy3Xhi1kClKiZ93X5P2JXSbrIn8Gmz0e1HIqJnE3ycbJ3KL5fYDYx3/MklxdnP0h9fva4LzOY+AIuwv6lLf4fnXHuPfFFIEcMZjMQDwBAbjjZz9ygkf3bIomTbRQYMG7vJi/XsxyM0ci6asNQfV5TAM62CIa7Rne9nRTkhHfZUSPcKw+ulkMZ0PlkYAzxlZWbbNvleiQ3ncrUwPp7VL6HXDPCgkYbL4xizMwyj4SP66eZDIoQw4KQ7GtGbbA6ljE34y7WtHrQh62gT5VxacF4z5tO3VFM9Ywg+1wtENd1oC8k5OHGRYYfk9Od5uJgj4p34G7/vR17gGO+Lhm2BYjLtPr7Gf4qv4hHHM3SDEy4imJRAtPOIoirdJigjejk1qBimtjwswjoa4JRc1MdTroCOg+VGX39V0VsvwNoOQ6ruUttUKipvrlVaDAHmkZivs8GSkNZpUIeOf0uDIju0ZoWxaU74CF+4B9PSFsgetmkxf8gcuWl0BswcFdzDnNQKx5Kav1vOpcxNIgzOrF2vcV5Zfc9HqqR2/lPEx5C1PCvVEj5ycqYlGonUVUB1ArFs6YTI5d+dEitBMNuk6/aQvp89E=
deploy:
- provider: script
  skip_cleanup: true
  script: lein release :patch
  on:
    branch: master
